apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: human-resources-4gw8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: human-resources-4gw8
    app.kubernetes.io/part-of: my-app
  name: human-resources-4gw8
  namespace: christianvogt-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: human-resources-4gw8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: human-resources-4gw8
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:paP4F-human-resources-4gw8
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
