apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: human-resources-4gw8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: human-resources-4gw8
    app.kubernetes.io/part-of: my-app
  name: human-resources-4gw8
  namespace: christianvogt-tenant
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: human-resources-4gw8
status:
  loadBalancer: {}
