apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-urqk
  namespace: christianvogt-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:afae18ad25f305a38b34973c560bd8afd23c473c8add4a1d325b46a54576c242
        name: my-nodejs
        resources: {}
status: {}
